# Generated by Django 6.0 on 2025-12-09 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ventasGuerrero', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VentasGuerro',
            new_name='ProductGuerrero',
        ),
    ]
