# Generated by Django 6.0 on 2026-01-10 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventasGuerrero", "0002_rename_ventasguerro_productguerrero"),
    ]

    operations = [
        migrations.AddField(
            model_name="productguerrero",
            name="tipe",
            field=models.CharField(
                choices=[
                    ("1", "Motos"),
                    ("2", "Tienda"),
                    ("3", "Pulguero de Guerrero"),
                ],
                default="1",
                max_length=1,
                verbose_name="Tipo de producto",
            ),
        ),
        migrations.AlterField(
            model_name="productguerrero",
            name="price",
            field=models.DecimalField(
                decimal_places=0, max_digits=10, verbose_name="Precio"
            ),
        ),
    ]
