# Generated by Django 6.0 on 2026-01-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ventasGuerrero", "0003_productguerrero_tipe_alter_productguerrero_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productguerrero",
            name="name",
            field=models.CharField(max_length=200, verbose_name="Nombre producto"),
        ),
    ]
